version: '3.3'  # Adjust this version if needed

services:
  db:
    image: postgres:17.0
    container_name: db_prod
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - swarm_network

  backend:
    image: swarmbackend:latest
    container_name: backend_prod
    restart: always
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Default=Host=db;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "8080:80"  # Maps host port 8080 to container port 80
      - "8443:443" # Maps host port 8443 to container port 443 (if using HTTPS)
    depends_on:
      - db
    networks:
      - swarm_network

volumes:
  postgres_data:

networks:
  swarm_network:
    driver: bridge