services:
  db:
    image: postgres:17.0
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: swarm
    ports:
      - 5432:5432
