name: Deploy Backend and Database
on:
  push:
    branches: [main]
    paths:
      - "SwarmBackend/**"
      - "swarm_ws/**"
      - "docker-compose.prod.yml"
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build Backend Docker image
        run: |
          docker build -t swarmbackend:latest -f SwarmBackend/Dockerfile .
      - name: Deploy with Docker Compose
        run: |
          docker-compose -f docker-compose.prod.yml down
          docker-compose -f docker-compose.prod.yml up -d
      # - name: Check logs
      #   run: |
      #     echo "Backend Logs:"
      #     docker-compose -f docker-compose.prod.yml logs backend
      #     echo "Database Logs:"
      #     docker-compose -f docker-compose.prod.yml logs db
      - name: Prune old Docker images
        run: docker system prune -af

      - name: Clean up old log files
        run: |
          echo "Cleaning up Docker logs older than 7 days..."
          docker system df
          journalctl --vacuum-time=7d 2>/dev/null || true
          echo "Log cleanup completed"

      - name: Give permission to script
        run: find . -type f -name "*.py" -exec chmod +x {} \;
